use livehealth;
create table region(r_id int,r_name varchar(25));
drop table region;
create table countries2(c_id int,c_name varchar(20),r_id int not null);
create table locations(l_id int,street varchar(20),post int,city int,state varchar(20),c_id int not null);
create table dept(d_id int, d_name varchar(15),manager varchar(10),l_id int not null);
create table employee(e_id int,f_name varchar(10),l_name varchar(10),email varchar(20),phno int,hiredate date,job_id varchar(10),salary int,comm int,m_id int, dept_id int);
desc employee;
desc locations;
create table jobs(j_id int,j_title varchar(10),min_sal int,max_sal int);
select count(job) from emp;
select * from emp;
select sum(sal) from emp;
select min(sal) from emp;
desc emp;
select max(sal)from emp where job="P" ;
select avg(sal),count(f_name) from emp where dept_id=101;
SELECT ROUND(MAX(sal),0) 'Maximum',ROUND(MIN(sal),0) 'Minimum',ROUND(SUM(sal),0) 'Sum',ROUND(AVG(sal),0) 'Average'FROM emp;
select count(f_name) from emp where job="P";
