print("All Arithmetic Operations : ")
a=int(input("Enter 1st Number : "))
b=int(input("Enter 2nd Number : "))
print('Addition = ',a+b)
print('Subtraction = ',a-b)
print('Multiplication = ',a*b)
print('Division = ',a/b)
